### ISSUE TITLE
Emoji Button doesn't import into Next.js

### ISSUE THREAD

**Issue by planktonrobo** [joeattardi/emoji-button#166]
I get the eorror

`SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@joeattardi/emoji-button (/Users/noahwardlow/dailyacts/.next/server/pages/index.js:499:18)
    at __webpack_require__ (/Users/noahwardlow/dailyacts/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/MainComp/NewArchiveName.js:6:82)`

**Comment by joeattardi** [comment]
Currently Emoji Button is only exported as an ES module. I believe that by default, Next.js does not do any transpilation of third party modules, so if you are using a browser that doesn't support ESM you will need to transpile Emoji Button.

I don't know a ton about Next.js but you could take a look at https://www.npmjs.com/package/next-transpile-modules
